# Generated by Django 5.2.3 on 2025-08-31 19:33

import cla.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CCLA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('corporation_address', models.CharField(blank=True, max_length=255)),
                ('corporation_alias', models.CharField(blank=True, max_length=255)),
                ('authorized_signer_email', models.EmailField(blank=True, max_length=254)),
                ('authorized_signer_name', models.CharField(blank=True, max_length=255)),
                ('corporation_name', models.CharField(max_length=255, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=255)),
                ('ccla_manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='CCLA manager')),
                ('authorized_signer_title', models.CharField(blank=True, max_length=255)),
                ('fax', models.CharField(blank=True, max_length=255)),
                ('docuseal_submission_id', models.IntegerField(blank=True, null=True)),
                ('cla_pdf', models.FileField(upload_to=cla.models.cla_file_name, verbose_name='CLA pdf')),
            ],
            options={
                'constraints': [],
                'verbose_name_plural': 'CCLAs',
                'verbose_name': 'CCLA',
            },
        ),
        migrations.CreateModel(
            name='CCLAAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=cla.models.ccla_attachment_name)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ccla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cla.ccla')),
            ],
            options={
                'verbose_name': 'CCLA Attachment',
                'verbose_name_plural': 'CCLA Attachments',
            },
        ),
        migrations.CreateModel(
            name='ICLA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('point_of_contact', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('docuseal_submission_id', models.IntegerField(blank=True, null=True)),
                ('mailing_address', models.CharField(blank=True, max_length=255)),
                ('public_name', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=255)),
                ('cla_pdf', models.FileField(upload_to=cla.models.cla_file_name, verbose_name='CLA pdf')),
                ('ccla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cla.ccla', verbose_name='CCLA')),
                ('in_schedule_a', models.BooleanField(default=False, verbose_name='In Schedule A')),
            ],
            options={
                'constraints': [],
                'verbose_name_plural': 'ICLAs',
                'verbose_name': 'ICLA',
            },
        ),
    ]
