# Generated by Django 5.2.3 on 2025-07-23 08:52

import cla.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CCLA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('corporation_address', models.CharField()),
                ('corporation_alias', models.CharField(blank=True)),
                ('authorized_signer_email', models.EmailField(max_length=254, unique=True)),
                ('authorized_signer_name', models.CharField()),
                ('corporation_name', models.CharField(unique=True)),
                ('telephone', models.CharField()),
                ('ccla_manager', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='CCLA manager')),
                ('authorized_signer_title', models.CharField(blank=True)),
                ('fax', models.CharField(blank=True)),
                ('docuseal_submission_id', models.IntegerField(blank=True, null=True)),
                ('cla_pdf', models.FileField(upload_to=cla.models.cla_file_name, verbose_name='CLA pdf')),
            ],
            options={
                'constraints': [],
                'verbose_name_plural': 'CCLAs',
                'verbose_name': 'CCLA',
            },
        ),
        migrations.CreateModel(
            name='ICLA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('employer_approved_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('full_name', models.CharField()),
                ('point_of_contact', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField()),
                ('docuseal_submission_id', models.IntegerField(blank=True, null=True)),
                ('mailing_address', models.CharField()),
                ('public_name', models.CharField(blank=True)),
                ('telephone', models.CharField(blank=True)),
                ('cla_pdf', models.FileField(upload_to=cla.models.cla_file_name, verbose_name='CLA pdf')),
                ('ccla_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='CCLA manager')),
            ],
            options={
                'constraints': [],
                'verbose_name_plural': 'ICLAs',
                'verbose_name': 'ICLA',
            },
        ),
    ]
