# Generated by Django 5.2.3 on 2025-06-25 14:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CCLA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('address', models.TextField()),
                ('alias', models.TextField(blank=True)),
                ('authorized_signer_email', models.EmailField(max_length=254, unique=True)),
                ('authorized_signer_name', models.TextField()),
                ('country', models.TextField()),
                ('legal_name', models.TextField(unique=True)),
                ('phone', models.TextField()),
                ('point_of_contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [],
            },
        ),
        migrations.CreateModel(
            name='ICLA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('employer_approved_at', models.DateTimeField(blank=True, null=True)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('full_name', models.TextField()),
                ('point_of_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('country', models.TextField(default='')),
                ('docuseal_submission_id', models.IntegerField(default='')),
                ('mailing_address', models.TextField(default='')),
                ('public_name', models.TextField(blank=True)),
                ('telephone', models.TextField(blank=True)),
            ],
            options={
                'constraints': [],
            },
        ),
    ]
