# Generated by Django 5.2.3 on 2025-06-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ccla',
            old_name='address',
            new_name='corporation_address',
        ),
        migrations.RenameField(
            model_name='ccla',
            old_name='alias',
            new_name='corporation_alias',
        ),
        migrations.RenameField(
            model_name='ccla',
            old_name='legal_name',
            new_name='corporation_name',
        ),
        migrations.RenameField(
            model_name='ccla',
            old_name='phone',
            new_name='telephone',
        ),
        migrations.RemoveField(
            model_name='ccla',
            name='country',
        ),
        migrations.AddField(
            model_name='ccla',
            name='authorized_signer_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ccla',
            name='fax',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='icla',
            name='country',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='icla',
            name='docuseal_submission_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='icla',
            name='mailing_address',
            field=models.TextField(),
        ),
    ]
