# Generated by Django 5.2.3 on 2025-08-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icla',
            name='mailing_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
