# Generated by Django 5.2.3 on 2025-08-29 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0002_alter_icla_mailing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='icla',
            name='ccla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cla.ccla', verbose_name='CCLA'),
        ),
    ]
