# Generated by Django 5.2.3 on 2025-09-10 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0002_alter_ccla_ccla_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='icla',
            name='is_volunteer',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is volunteer'),
        ),
    ]
