# Generated by Django 5.2.3 on 2025-06-27 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0002_rename_address_ccla_corporation_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccla',
            name='docuseal_submission_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
