# Generated by Django 5.2.3 on 2025-08-31 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0002_alter_ccla_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icla',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
