# Generated by Django 5.2.3 on 2025-07-01 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0003_ccla_docuseal_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccla',
            name='authorized_signer_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='ccla',
            name='authorized_signer_title',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='ccla',
            name='corporation_address',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='ccla',
            name='corporation_alias',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='ccla',
            name='corporation_name',
            field=models.CharField(unique=True),
        ),
        migrations.AlterField(
            model_name='ccla',
            name='fax',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='ccla',
            name='telephone',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='icla',
            name='country',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='icla',
            name='full_name',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='icla',
            name='mailing_address',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='icla',
            name='public_name',
            field=models.CharField(blank=True),
        ),
        migrations.AlterField(
            model_name='icla',
            name='telephone',
            field=models.CharField(blank=True),
        ),
    ]
