# Generated by Django 5.2.3 on 2025-08-29 13:50

import cla.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0003_icla_ccla'),
    ]

    operations = [
        migrations.CreateModel(
            name='CCLAAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=cla.models.ccla_attachment_name)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ccla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='cla.ccla')),
            ],
            options={
                'verbose_name': 'CCLA Attachment',
                'verbose_name_plural': 'CCLA Attachments',
            },
        ),
    ]
