# Generated by Django 5.2.3 on 2025-09-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0003_icla_is_volunteer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icla',
            old_name='is_volunteer',
            new_name='_is_volunteer',
        ),
    ]
