# Generated by Django 5.2.3 on 2025-07-18 08:58

import cla.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0004_alter_ccla_authorized_signer_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ccla',
            options={'verbose_name_plural': 'CCLAs'},
        ),
        migrations.AlterModelOptions(
            name='icla',
            options={'verbose_name_plural': 'ICLAs'},
        ),
        migrations.AddField(
            model_name='ccla',
            name='cla_pdf',
            field=models.FileField(default='', upload_to=cla.models.cla_file_name),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icla',
            name='cla_pdf',
            field=models.FileField(default='', upload_to=cla.models.cla_file_name),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ccla',
            name='docuseal_submission_id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='icla',
            name='docuseal_submission_id',
            field=models.IntegerField(blank=True),
        ),
    ]
