# Generated by Django 5.2.3 on 2025-08-29 17:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0004_cclaattachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icla',
            name='ccla_manager',
        ),
        migrations.AlterField(
            model_name='cclaattachment',
            name='ccla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cla.ccla'),
        ),
    ]
