# Generated by Django 5.2.3 on 2025-09-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0004_rename_is_volunteer_icla__is_volunteer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icla',
            name='_is_volunteer',
            field=models.BooleanField(default=True, verbose_name='Is volunteer'),
        ),
    ]
