# Generated by Django 5.2.3 on 2025-07-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0005_alter_ccla_options_alter_icla_options_ccla_cla_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccla',
            name='docuseal_submission_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='icla',
            name='docuseal_submission_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
