# Generated by Django 5.2.3 on 2025-09-20 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0005_alter_icla__is_volunteer'),
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icla',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iclas', to='personnel.person', verbose_name='Personnel Person'),
        ),
    ]
