# Generated by Django 5.2.3 on 2025-08-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0005_remove_icla_ccla_manager_alter_cclaattachment_ccla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icla',
            name='employer_approved_at',
        ),
        migrations.AddField(
            model_name='icla',
            name='in_schedule_a',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
