# Generated by Django 5.2.3 on 2025-07-21 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0006_alter_ccla_docuseal_submission_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ccla',
            old_name='point_of_contact',
            new_name='ccla_manager',
        ),
        migrations.AddField(
            model_name='icla',
            name='ccla_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='icla',
            name='point_of_contact',
            field=models.EmailField(blank=True, default='', max_length=254),
            preserve_default=False,
        ),
    ]
