# Generated by Django 5.2.3 on 2025-08-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0006_remove_icla_employer_approved_at_icla_in_schedule_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icla',
            name='in_schedule_a',
            field=models.BooleanField(default=False),
        ),
    ]
