# Generated by Django 5.2.3 on 2025-07-21 15:15

import cla.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0007_rename_point_of_contact_ccla_ccla_manager_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ccla',
            options={'verbose_name': 'CCLA', 'verbose_name_plural': 'CCLAs'},
        ),
        migrations.AlterModelOptions(
            name='icla',
            options={'verbose_name': 'ICLA', 'verbose_name_plural': 'ICLAs'},
        ),
        migrations.AlterField(
            model_name='ccla',
            name='ccla_manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='CCLA manager'),
        ),
        migrations.AlterField(
            model_name='ccla',
            name='cla_pdf',
            field=models.FileField(upload_to=cla.models.cla_file_name, verbose_name='CLA pdf'),
        ),
        migrations.AlterField(
            model_name='icla',
            name='ccla_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='CCLA manager'),
        ),
        migrations.AlterField(
            model_name='icla',
            name='cla_pdf',
            field=models.FileField(upload_to=cla.models.cla_file_name, verbose_name='CLA pdf'),
        ),
    ]
