# Generated by Django 5.2.3 on 2025-08-31 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0007_alter_icla_in_schedule_a'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccla',
            name='authorized_signer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='icla',
            name='in_schedule_a',
            field=models.BooleanField(default=False, verbose_name='In Schedule A'),
        ),
    ]
