# Generated by Django 5.2.3 on 2025-08-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0008_alter_ccla_authorized_signer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccla',
            name='authorized_signer_email',
            field=models.EmailField(blank=True, default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ccla',
            name='authorized_signer_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
