# Generated by Django 5.2.3 on 2025-08-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cla', '0009_alter_ccla_authorized_signer_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccla',
            name='corporation_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ccla',
            name='telephone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='icla',
            name='country',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
