# Generated by Django 5.2.3 on 2025-09-20 16:27
import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("since", models.DateField(blank=True, null=True)),
                ("until", models.DateField(blank=True, null=True)),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="personnel.group")),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("country", models.CharField(blank=True, max_length=255)),
                ("joined_at", models.DateField(blank=True, null=True)),
                ("github", models.CharField(blank=True, max_length=255, unique=True)),
                ("ghe", models.CharField(blank=True, max_length=255, unique=True, verbose_name="GHE")),
                ("nick", models.CharField(blank=True, max_length=255)),
                ("rev", models.CharField(blank=True, max_length=255, unique=True)),
                ("pgp", models.CharField(blank=True, max_length=255, unique=True, verbose_name="PGP")),
                (
                    "groups",
                    models.ManyToManyField(
                        related_name="members",
                        through="personnel.Membership",
                        through_fields=("person", "group"),
                        to="personnel.group",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Personnel",
            },
        ),
        migrations.AddField(
            model_name="membership",
            name="person",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="personnel.person"),
        ),
        migrations.CreateModel(
            name="Identity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("identity", models.CharField(max_length=255)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="identities", to="personnel.person"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Email",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="emails", to="personnel.person"
                    ),
                ),
            ],
        ),
    ]
