# Generated by Django 5.2.3 on 2025-09-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='ghe',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='GHE'),
        ),
        migrations.AlterField(
            model_name='person',
            name='github',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='pgp',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='PGP'),
        ),
        migrations.AlterField(
            model_name='person',
            name='rev',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
