# Generated by Django 5.2.3 on 2025-09-28 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_alter_person_ghe_alter_person_github_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='identity',
            options={'verbose_name_plural': 'Identities'},
        ),
    ]
